package(default_visibility = ["//visibility:public"])

cc_library(
    name = "port",
    srcs = [
        "port.cc",
    ],
    hdrs = [
        "port.h"
    ],
    deps = [
        "@com_github_glog_glog//:glog",
    ]
)